#!/bin/bash

# Command dictionnary
declare -A commands
commands['build']="docker-compose build"
commands['start']="docker-compose up -d"
commands['stop']="docker-compose stop"
commands['tu']="docker-compose exec server /venv/bin/python -m unittest"
commands['bash']="docker-compose exec backend /bin/bash"
commands['logs']="docker-compose logs $2"
commands['shell']="docker-compose exec backend /venv/bin/ipython3"
commands['stop-all']="docker stop $(docker ps -q)"
commands['manage']="docker-compose exec backend /app/manage.py $2 $3 $4 $5"
commands['migrate']="docker-compose exec backend /app/manage.py migrate $2 $3 $4"
commands['createsuperuser']="docker-compose exec backend /app/manage.py createsuperuser"
#commands['']=

if [ -v commands[$1] ]; 
then
    ${commands[$1]}
else
    echo "build: build containers"
    echo "start: start project"
    echo "shell: start ipython shell"
    echo "bash: start bash for backend"
    echo "stop: stop project's container"
    echo "stop-all: stop all docker containers"
    echo "manage: django's manage.py"
fi