#!/bin/bash

# Command dictionnary
declare -A commands
commands['build']="docker-compose build"
commands['start']="docker-compose up -d"
commands['stop']="docker-compose stop"
commands['tu']="docker-compose exec server /venv/bin/python -m unittest"
commands['bash']="docker-compose exec backend /bin/bash"
commands['logs']="docker-compose logs"
commands['shell']="docker-compose exec server /venv/bin/ipython3"
commands['stop-all']="docker stop $(docker ps -q)"
#commands['']=

if [ -v commands[$1] ]; 
then
    ${commands[$1]}
else
    echo "build: build containers"
    echo "start: start project"
    echo "bash: start bash for backend"
    echo "stop: stop project's container"
    echo "stop-all: stop all docker containers"
fi