# Generated by Django 3.2 on 2021-05-02 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('gifs', '0002_alter_gif_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gif',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='gif',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
