# Generated by Django 3.2 on 2021-05-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_auto_20210502_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gif',
            old_name='title',
            new_name='name',
        ),
    ]
