# Generated by Django 3.2 on 2021-05-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210502_1408'),
        ('gifs', '0004_rename_title_gif_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
